import type { Metadata } from 'next';
import { Montserrat, Sora } from 'next/font/google';
import './global.scss';
import Navbar from '@/components/nav/NavBar';
import Footer from '@/components/footer/footer';
import WhatsAppButton from '@/components/wahtsAppButton/whatsAppButton';

const geistSans = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-montserrat',
});
const geistSora = Sora({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-sora',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistSora.variable}  antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        <WhatsAppButton />
      </body>
    </html>
  );
}
